<a href="https://colab.research.google.com/github/srinidhi222/school-fees-managment/blob/main/school_fees_managment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import sqlite3

def create_database():
    # Connect to SQLite database (or create it if it doesn't exist)
    conn = sqlite3.connect('school_fees_management.db')
    cursor = conn.cursor()

    # Create Students table
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS students (
            student_id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            class TEXT NOT NULL,
            fees_paid REAL DEFAULT 0,
            total_fees REAL NOT NULL
        )
    ''')

    # Create Payments table
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS payments (
            payment_id INTEGER PRIMARY KEY AUTOINCREMENT,
            student_id INTEGER,
            amount REAL NOT NULL,
            payment_date DATE NOT NULL,
            FOREIGN KEY (student_id) REFERENCES students (student_id)
        )
    ''')

    # Commit changes and close the connection
    conn.commit()
    conn.close()

if __name__ == "__main__":
    create_database()
    print("Database and tables created successfully.")

Database and tables created successfully.

In [4]:
import sqlite3
from datetime import datetime

def connect_db():
    return sqlite3.connect('school_fees_management.db')

def add_student(name, class_name, total_fees):
    conn = connect_db()
    cursor = conn.cursor()
    cursor.execute('''
        INSERT INTO students (name, class, total_fees) VALUES (?, ?, ?)
    ''', (name, class_name, total_fees))
    conn.commit()
    conn.close()
    print("Student added successfully.")

def view_students():
    conn = connect_db()
    cursor = conn.cursor()
    cursor.execute('SELECT * FROM students')
    students = cursor.fetchall()
    conn.close()
    return students

def record_payment(student_id, amount):
    conn = connect_db()
    cursor = conn.cursor()
    cursor.execute('''
        INSERT INTO payments (student_id, amount, payment_date) VALUES (?, ?, ?)
    ''', (student_id, amount, datetime.now().date()))

    # Update the fees paid in the students table
    cursor.execute('''
        UPDATE students SET fees_paid = fees_paid + ? WHERE student_id = ?
    ''', (amount, student_id))

    conn.commit()
    conn.close()
    print("Payment recorded successfully.")

def view_payments():
    conn = connect_db()
    cursor = conn.cursor()
    cursor.execute('''
        SELECT p.payment_id, s.name, p.amount, p.payment_date
        FROM payments p
        JOIN students s ON p.student_id = s.student_id
    ''')
    payments = cursor.fetchall()
    conn.close()
    return payments

def main():
    while True:
        print("\nSchool Fees Management System")
        print("1. Add Student")
        print("2. View Students")
        print("3. Record Payment")
        print("4. View Payments")
        print("5. Exit")

        choice = input("Enter your choice: ")

        if choice == '1':
            name = input("Enter student name: ")
            class_name = input("Enter class: ")
            total_fees = float(input("Enter total fees: "))
            add_student(name, class_name, total_fees)

        elif choice == '2':
            students = view_students()
            print("\nStudents:")
            for student in students:
                print(f"ID: {student[0]}, Name: {student[1]}, Class: {student[2]}, Fees Paid: {student[3]}, Total Fees: {student[4]}")
import sqlite3
from datetime import datetime

def connect_db():
    return sqlite3.connect('school_fees_management.db')

def add_student(name, class_name, total_fees):
    conn = connect_db()
    cursor = conn.cursor()
    cursor.execute('''
        INSERT INTO students (name, class, total_fees) VALUES (?, ?, ?)
    ''', (name, class_name, total_fees))
    conn.commit()
    conn.close()
    print("Student added successfully.")

def view_students():
    conn = connect_db()
    cursor = conn.cursor()
    cursor.execute('SELECT * FROM students')
    students = cursor.fetchall()
    conn.close()
    return students

def record_payment(student_id, amount):
    conn = connect_db()
    cursor = conn.cursor()
    cursor.execute('''
        INSERT INTO payments (student_id, amount, payment_date) VALUES (?, ?, ?)
    ''', (student_id, amount, datetime.now().date()))

    # Update the fees paid in the students table
    cursor.execute('''
        UPDATE students SET fees_paid = fees_paid + ? WHERE student_id = ?
    ''', (amount, student_id))

    conn.commit()
    conn.close()
    print("Payment recorded successfully.")

def view_payments():
    conn = connect_db()
    cursor = conn.cursor()
    cursor.execute('''
        SELECT p.payment_id, s.name, p.amount, p.payment_date
        FROM payments p
        JOIN students s ON p.student_id = s.student_id
    ''')
    payments = cursor.fetchall()
    conn.close()
    return payments

def main():
    while True:
        print("\nSchool Fees Management System")
        print("1. Add Student")
        print("2. View Students")
        print("3. Record Payment")
        print("4. View Payments")
        print("5. Exit")

        choice = input("Enter your choice: ")

        if choice == '1':
            name = input("Enter student name: ")
            class_name = input("Enter class: ")
            total_fees = float(input("Enter total fees: "))
            add_student(name, class_name, total_fees)

        elif choice == '2':
            students = view_students()
            print("\nStudents:")
            for student in students:
                print(f"ID: {student[0]}, Name: {student[1]}, Class: {student[2]}, Fees Paid: {student[3]}, Total Fees: {student[4]}")

        elif choice == '3':
            student_id = int(input("Enter student ID: "))
            amount = float(input("Enter amount paid: "))
            record_payment(student_id, amount)

        elif choice == '4':
            payments = view_payments()
            print("\nPayments:")
            for payment in payments:
                print(f"ID: {payment[0]}, Student: {payment[1]}, Amount: {payment[2]}, Date: {payment[3]}")

        elif choice == '5':
            break

        else:
            print("Invalid choice. Please try again.")

if __name__ == "__main__":
    main()

School Fees Management System
1. Add Student
2. View Students
3. Record Payment
4. View Payments
5. Exit
Enter your choice: 4

Payments:
ID: 1, Student: Srinidhi, Amount: 50000.0, Date: 2025-06-26

School Fees Management System
1. Add Student
2. View Students
3. Record Payment
4. View Payments
5. Exit
Enter your choice: 1
Enter student name: Bob
Enter class: 9
Enter total fees: 55000
Student added successfully.

School Fees Management System
1. Add Student
2. View Students
3. Record Payment
4. View Payments
5. Exit
Enter your choice: 3
Enter student ID: 2
Enter amount paid: 45
Payment recorded successfully.

School Fees Management System
1. Add Student
2. View Students
3. Record Payment
4. View Payments
5. Exit
Enter your choice: 3
Enter student ID: 45000
Enter amount paid: 4
Payment recorded successfully.

School Fees Management System
1. Add Student
2. View Students
3. Record Payment
4. View Payments
5. Exit
Enter your choice: 2

Students:
ID: 1, Name: Srinidhi, Class: 8, Fees Paid: 50000.0, Total Fees: 50000.0
ID: 2, Name: Bob, Class: 9, Fees Paid: 45.0, Total Fees: 55000.0

School Fees Management System
1. Add Student
2. View Students
3. Record Payment
4. View Payments
5. Exit
Enter your choice: 5